### ISSUE TITLE
RTSI setup recipe fail

### ISSUE THREAD

**Issue by haub94** [Elite-Robots/Elite_Robots_CS_SDK#3]
I tried to run the trajectory_example, but i got the error 
`[FATAL] source/Rtsi/RtsiIOInterface.cpp:46: RTSI setup recipe fail. Check recipe files.` 
and 
`[ERROR] source/Control/ScriptSender.cpp:38: Script sender receive fail: End of file [asio.misc:2 at /usr/include/boost/asio/detail/reactive_socket_recv_op.hpp:133 in function 'do_complete']`

I tested the rtsi_example and its the same behavior. 

I installed the SDK accordingly to the notes from the README. The Dashboard- and the EliteDriver-example works well. It looks like an fault within the recipe but without docu its hard to debug this. **Can you have an eye on this please?!**

**Specs:**
I´m working on ManjaroLinux 24.2.0
Cobot: 
CS63 
RT ROBOT V2.12.0.21
RT SERVER V2.12.0.8594

**Log:**
Dashboard connected 
[FATAL] source/Rtsi/RtsiIOInterface.cpp:46: RTSI setup recipe fail. Check recipe files.
RTSI connected
Robot power on
Robot brake released
[INFO] source/Control/ScriptSender.cpp:16: Script sender accept new connection.
[INFO] source/Control/ScriptSender.cpp:36: Robot request external control script.
[INFO] source/Control/ScriptSender.cpp:36: Robot request external control script.
[ERROR] source/Control/ScriptSender.cpp:38: Script sender receive fail: End of file [asio.misc:2 at /usr/include/boost/asio/detail/reactive_socket_recv_op.hpp:133 in function 'do_complete']
Program run
[INFO] source/Control/TrajectoryInterface.cpp:15: Trajectory interface accept new connection.
//robot moves...

**Comment by SupermanOfHeiLinPu** [comment]
You need to upgrade your RT ROBOT and RT SERVER to version 2.13 or above. Alternatively, you can delete the two items "tool_digital_output_mask" and "tool_digital_output" in the "input_recipe.txt" file, but if you do so, you will not be able to set the tool array IO. @haub94

**Comment by haub94** [comment]
Thanks for the fast response!
Currently its possible to download v2.11.0 (eup) and v2.12.0.3 (eru) only. Can you push the current versions to the [download-hub](https://de.eliterobots.com/download)?!

For now your recommended workaround fixed it and I`m fine with this. But for others it would be nice to have the newest RT versions.
